# Generated by Django 2.1.8 on 2020-03-23 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myMember', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
