# Generated by Django 2.1.8 on 2020-04-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_auto_20200330_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='create_img',
            field=models.ImageField(blank=True, null=True, upload_to='post/%Y/%m/%d'),
        ),
    ]
