# Generated by Django 2.1.8 on 2020-05-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_auto_20200415_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name_2', models.CharField(max_length=140, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='tag_set_2',
            field=models.ManyToManyField(blank=True, to='myApp.Tag_2'),
        ),
    ]
